/** Seeded from the repo's IntegrationsSection brand list. */
export const integrations = [
  { name: "HubSpot", iconSlug: "hubspot", category: "crm" },
  { name: "Zapier", iconSlug: "zapier", category: "automation" },
  { name: "Make", iconSlug: "make", category: "automation" },
  { name: "n8n", iconSlug: "n8n", category: "automation" },
  { name: "Notion", iconSlug: "notion", category: "productivity" },
  { name: "Jira", iconSlug: "jira", category: "productivity" },
  { name: "Gmail", iconSlug: "gmail", category: "productivity" },
  { name: "Google Calendar", iconSlug: "googlecalendar", category: "productivity" },
  { name: "Google Sheets", iconSlug: "googlesheets", category: "productivity" },
  { name: "Google Drive", iconSlug: "googledrive", category: "productivity" },
  { name: "Dropbox", iconSlug: "dropbox", category: "productivity" },
  { name: "Intercom", iconSlug: "intercom", category: "support" },
  { name: "Zendesk", iconSlug: "zendesk", category: "support" },
  { name: "Zoho", iconSlug: "zoho", category: "crm" },
  { name: "Asana", iconSlug: "asana", category: "productivity" },
  { name: "Trello", iconSlug: "trello", category: "productivity" },
  { name: "ClickUp", iconSlug: "clickup", category: "productivity" },
  { name: "Airtable", iconSlug: "airtable", category: "productivity" },
  { name: "Calendly", iconSlug: "calendly", category: "productivity" },
  { name: "WhatsApp", iconSlug: "whatsapp", category: "messaging" },
  { name: "Telegram", iconSlug: "telegram", category: "messaging" },
  { name: "Zoom", iconSlug: "zoom", category: "productivity" },
  { name: "Shopify", iconSlug: "shopify", category: "commerce" },
  { name: "WooCommerce", iconSlug: "woocommerce", category: "commerce" },
  { name: "WordPress", iconSlug: "wordpress", category: "commerce" },
  { name: "Mailchimp", iconSlug: "mailchimp", category: "automation" },
  { name: "Stripe", iconSlug: "stripe", category: "finance" },
  { name: "PayPal", iconSlug: "paypal", category: "finance" },
  { name: "Square", iconSlug: "square", category: "finance" },
  { name: "QuickBooks", iconSlug: "quickbooks", category: "finance" },
  { name: "Xero", iconSlug: "xero", category: "finance" },
  { name: "Google Analytics", iconSlug: "googleanalytics", category: "other" },
] as const;
