/** Seeded from the repo's SiteHeader / SiteFooter navigation. */
export const siteSettings = {
  brandName: "Smartytel",
  footerNote:
    "One business phone for your whole team — with local and toll-free numbers across the US, Canada, the UK and every European country.",
  footerColumns: [
    {
      heading: "Product",
      links: [
        { label: "Calling", to: "/calling" },
        { label: "Text messaging", to: "/messaging" },
        { label: "Phone menu & routing", to: "/phone-menu" },
        { label: "Shared numbers", to: "/shared-numbers" },
        { label: "CRM", to: "/crm" },
        { label: "Analytics & oversight", to: "/analytics" },
        { label: "Sona AI agent", to: "/ai-agent" },
        { label: "Integrations", to: "/integrations" },
        { label: "Smartytel API", to: "/developers" },
      ],
    },
    {
      heading: "Solutions",
      links: [
        { label: "Home services", to: "/solutions/home-services" },
        { label: "Law firms", to: "/solutions/law-firms" },
        { label: "Property management", to: "/solutions/property-management" },
        { label: "Healthcare", to: "/solutions/healthcare" },
        { label: "Startups", to: "/solutions/startups" },
        { label: "Small business", to: "/solutions/small-business" },
        { label: "Sales teams", to: "/solutions/sales" },
        { label: "Support teams", to: "/solutions/support" },
      ],
    },
    {
      heading: "Resources",
      links: [
        { label: "Blog", to: "/blog" },
        { label: "Guides", to: "/resources" },
        { label: "Developer docs", to: "/docs" },
        { label: "Number porting", to: "/port-your-number" },
        { label: "Customers", to: "/customers" },
        { label: "Product demo", to: "/demo" },
        { label: "Status", to: "/status" },
      ],
    },
    {
      heading: "Company",
      links: [
        { label: "About us", to: "/about" },
        { label: "Careers", to: "/careers" },
        { label: "Partners", to: "/partners" },
        { label: "Contact sales", to: "/contact" },
        { label: "Pricing", to: "/pricing" },
      ],
    },
  ],
  regions: [
    "United States",
    "Canada",
    "United Kingdom",
    "Ireland",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Netherlands",
    "Belgium",
    "Poland",
    "Sweden",
    "Denmark",
    "Norway",
    "Finland",
    "Portugal",
    "Austria",
    "Switzerland",
    "Czechia",
    "Romania",
  ].map((value) => ({ value })),
} as const;
