/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125AiAgentRouteImport } from './routes/{-$locale}/ai-agent'
import { Route as Char123LocaleChar125AnalyticsRouteImport } from './routes/{-$locale}/analytics'
import { Route as Char123LocaleChar125BlogRouteImport } from './routes/{-$locale}/blog'
import { Route as Char123LocaleChar125CallingRouteImport } from './routes/{-$locale}/calling'
import { Route as Char123LocaleChar125CareersRouteImport } from './routes/{-$locale}/careers'
import { Route as Char123LocaleChar125ConnectivityRouteImport } from './routes/{-$locale}/connectivity'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125CrmRouteImport } from './routes/{-$locale}/crm'
import { Route as Char123LocaleChar125CustomersRouteImport } from './routes/{-$locale}/customers'
import { Route as Char123LocaleChar125DemoRouteImport } from './routes/{-$locale}/demo'
import { Route as Char123LocaleChar125DevelopersRouteImport } from './routes/{-$locale}/developers'
import { Route as Char123LocaleChar125DocsRouteImport } from './routes/{-$locale}/docs'
import { Route as Char123LocaleChar125DownloadsRouteImport } from './routes/{-$locale}/downloads'
import { Route as Char123LocaleChar125GdprRouteImport } from './routes/{-$locale}/gdpr'
import { Route as Char123LocaleChar125IntegrationsRouteImport } from './routes/{-$locale}/integrations'
import { Route as Char123LocaleChar125LlmInfoRouteImport } from './routes/{-$locale}/llm-info'
import { Route as Char123LocaleChar125MessagingRouteImport } from './routes/{-$locale}/messaging'
import { Route as Char123LocaleChar125PartnersRouteImport } from './routes/{-$locale}/partners'
import { Route as Char123LocaleChar125PhoneMenuRouteImport } from './routes/{-$locale}/phone-menu'
import { Route as Char123LocaleChar125PortYourNumberRouteImport } from './routes/{-$locale}/port-your-number'
import { Route as Char123LocaleChar125PricingRouteImport } from './routes/{-$locale}/pricing'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125RefundRouteImport } from './routes/{-$locale}/refund'
import { Route as Char123LocaleChar125ResourcesRouteImport } from './routes/{-$locale}/resources'
import { Route as Char123LocaleChar125SecurityRouteImport } from './routes/{-$locale}/security'
import { Route as Char123LocaleChar125SharedNumbersRouteImport } from './routes/{-$locale}/shared-numbers'
import { Route as Char123LocaleChar125StatusRouteImport } from './routes/{-$locale}/status'
import { Route as Char123LocaleChar125TasksRouteImport } from './routes/{-$locale}/tasks'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as ApiPublicRatesSheetRouteImport } from './routes/api/public/rates-sheet'
import { Route as Char123LocaleChar125RatesIndexRouteImport } from './routes/{-$locale}/rates.index'
import { Route as Char123LocaleChar125RatesCountrySlugRouteImport } from './routes/{-$locale}/rates.$countrySlug'
import { Route as Char123LocaleChar125SolutionsEducationRouteImport } from './routes/{-$locale}/solutions.education'
import { Route as Char123LocaleChar125SolutionsFranchiseRouteImport } from './routes/{-$locale}/solutions.franchise'
import { Route as Char123LocaleChar125SolutionsHealthcareRouteImport } from './routes/{-$locale}/solutions.healthcare'
import { Route as Char123LocaleChar125SolutionsHomeServicesRouteImport } from './routes/{-$locale}/solutions.home-services'
import { Route as Char123LocaleChar125SolutionsLawFirmsRouteImport } from './routes/{-$locale}/solutions.law-firms'
import { Route as Char123LocaleChar125SolutionsOperationsRouteImport } from './routes/{-$locale}/solutions.operations'
import { Route as Char123LocaleChar125SolutionsPropertyManagementRouteImport } from './routes/{-$locale}/solutions.property-management'
import { Route as Char123LocaleChar125SolutionsSalesRouteImport } from './routes/{-$locale}/solutions.sales'
import { Route as Char123LocaleChar125SolutionsSmallBusinessRouteImport } from './routes/{-$locale}/solutions.small-business'
import { Route as Char123LocaleChar125SolutionsStartupsRouteImport } from './routes/{-$locale}/solutions.startups'
import { Route as Char123LocaleChar125SolutionsSupportRouteImport } from './routes/{-$locale}/solutions.support'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AiAgentRoute =
  Char123LocaleChar125AiAgentRouteImport.update({
    id: '/{-$locale}/ai-agent',
    path: '/{-$locale}/ai-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AnalyticsRoute =
  Char123LocaleChar125AnalyticsRouteImport.update({
    id: '/{-$locale}/analytics',
    path: '/{-$locale}/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogRoute =
  Char123LocaleChar125BlogRouteImport.update({
    id: '/{-$locale}/blog',
    path: '/{-$locale}/blog',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CallingRoute =
  Char123LocaleChar125CallingRouteImport.update({
    id: '/{-$locale}/calling',
    path: '/{-$locale}/calling',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CareersRoute =
  Char123LocaleChar125CareersRouteImport.update({
    id: '/{-$locale}/careers',
    path: '/{-$locale}/careers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ConnectivityRoute =
  Char123LocaleChar125ConnectivityRouteImport.update({
    id: '/{-$locale}/connectivity',
    path: '/{-$locale}/connectivity',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/{-$locale}/contact',
    path: '/{-$locale}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CrmRoute = Char123LocaleChar125CrmRouteImport.update({
  id: '/{-$locale}/crm',
  path: '/{-$locale}/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125CustomersRoute =
  Char123LocaleChar125CustomersRouteImport.update({
    id: '/{-$locale}/customers',
    path: '/{-$locale}/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DemoRoute =
  Char123LocaleChar125DemoRouteImport.update({
    id: '/{-$locale}/demo',
    path: '/{-$locale}/demo',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DevelopersRoute =
  Char123LocaleChar125DevelopersRouteImport.update({
    id: '/{-$locale}/developers',
    path: '/{-$locale}/developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsRoute =
  Char123LocaleChar125DocsRouteImport.update({
    id: '/{-$locale}/docs',
    path: '/{-$locale}/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DownloadsRoute =
  Char123LocaleChar125DownloadsRouteImport.update({
    id: '/{-$locale}/downloads',
    path: '/{-$locale}/downloads',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125GdprRoute =
  Char123LocaleChar125GdprRouteImport.update({
    id: '/{-$locale}/gdpr',
    path: '/{-$locale}/gdpr',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IntegrationsRoute =
  Char123LocaleChar125IntegrationsRouteImport.update({
    id: '/{-$locale}/integrations',
    path: '/{-$locale}/integrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LlmInfoRoute =
  Char123LocaleChar125LlmInfoRouteImport.update({
    id: '/{-$locale}/llm-info',
    path: '/{-$locale}/llm-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MessagingRoute =
  Char123LocaleChar125MessagingRouteImport.update({
    id: '/{-$locale}/messaging',
    path: '/{-$locale}/messaging',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PartnersRoute =
  Char123LocaleChar125PartnersRouteImport.update({
    id: '/{-$locale}/partners',
    path: '/{-$locale}/partners',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PhoneMenuRoute =
  Char123LocaleChar125PhoneMenuRouteImport.update({
    id: '/{-$locale}/phone-menu',
    path: '/{-$locale}/phone-menu',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PortYourNumberRoute =
  Char123LocaleChar125PortYourNumberRouteImport.update({
    id: '/{-$locale}/port-your-number',
    path: '/{-$locale}/port-your-number',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PricingRoute =
  Char123LocaleChar125PricingRouteImport.update({
    id: '/{-$locale}/pricing',
    path: '/{-$locale}/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/{-$locale}/privacy',
    path: '/{-$locale}/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125RefundRoute =
  Char123LocaleChar125RefundRouteImport.update({
    id: '/{-$locale}/refund',
    path: '/{-$locale}/refund',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ResourcesRoute =
  Char123LocaleChar125ResourcesRouteImport.update({
    id: '/{-$locale}/resources',
    path: '/{-$locale}/resources',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SecurityRoute =
  Char123LocaleChar125SecurityRouteImport.update({
    id: '/{-$locale}/security',
    path: '/{-$locale}/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SharedNumbersRoute =
  Char123LocaleChar125SharedNumbersRouteImport.update({
    id: '/{-$locale}/shared-numbers',
    path: '/{-$locale}/shared-numbers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125StatusRoute =
  Char123LocaleChar125StatusRouteImport.update({
    id: '/{-$locale}/status',
    path: '/{-$locale}/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TasksRoute =
  Char123LocaleChar125TasksRouteImport.update({
    id: '/{-$locale}/tasks',
    path: '/{-$locale}/tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/{-$locale}/terms',
    path: '/{-$locale}/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRatesSheetRoute = ApiPublicRatesSheetRouteImport.update({
  id: '/api/public/rates-sheet',
  path: '/api/public/rates-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RatesIndexRoute =
  Char123LocaleChar125RatesIndexRouteImport.update({
    id: '/{-$locale}/rates/',
    path: '/{-$locale}/rates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125RatesCountrySlugRoute =
  Char123LocaleChar125RatesCountrySlugRouteImport.update({
    id: '/{-$locale}/rates/$countrySlug',
    path: '/{-$locale}/rates/$countrySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsEducationRoute =
  Char123LocaleChar125SolutionsEducationRouteImport.update({
    id: '/{-$locale}/solutions/education',
    path: '/{-$locale}/solutions/education',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsFranchiseRoute =
  Char123LocaleChar125SolutionsFranchiseRouteImport.update({
    id: '/{-$locale}/solutions/franchise',
    path: '/{-$locale}/solutions/franchise',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsHealthcareRoute =
  Char123LocaleChar125SolutionsHealthcareRouteImport.update({
    id: '/{-$locale}/solutions/healthcare',
    path: '/{-$locale}/solutions/healthcare',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsHomeServicesRoute =
  Char123LocaleChar125SolutionsHomeServicesRouteImport.update({
    id: '/{-$locale}/solutions/home-services',
    path: '/{-$locale}/solutions/home-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsLawFirmsRoute =
  Char123LocaleChar125SolutionsLawFirmsRouteImport.update({
    id: '/{-$locale}/solutions/law-firms',
    path: '/{-$locale}/solutions/law-firms',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsOperationsRoute =
  Char123LocaleChar125SolutionsOperationsRouteImport.update({
    id: '/{-$locale}/solutions/operations',
    path: '/{-$locale}/solutions/operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsPropertyManagementRoute =
  Char123LocaleChar125SolutionsPropertyManagementRouteImport.update({
    id: '/{-$locale}/solutions/property-management',
    path: '/{-$locale}/solutions/property-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsSalesRoute =
  Char123LocaleChar125SolutionsSalesRouteImport.update({
    id: '/{-$locale}/solutions/sales',
    path: '/{-$locale}/solutions/sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsSmallBusinessRoute =
  Char123LocaleChar125SolutionsSmallBusinessRouteImport.update({
    id: '/{-$locale}/solutions/small-business',
    path: '/{-$locale}/solutions/small-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsStartupsRoute =
  Char123LocaleChar125SolutionsStartupsRouteImport.update({
    id: '/{-$locale}/solutions/startups',
    path: '/{-$locale}/solutions/startups',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SolutionsSupportRoute =
  Char123LocaleChar125SolutionsSupportRouteImport.update({
    id: '/{-$locale}/solutions/support',
    path: '/{-$locale}/solutions/support',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/ai-agent': typeof Char123LocaleChar125AiAgentRoute
  '/{-$locale}/analytics': typeof Char123LocaleChar125AnalyticsRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRoute
  '/{-$locale}/calling': typeof Char123LocaleChar125CallingRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/connectivity': typeof Char123LocaleChar125ConnectivityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/crm': typeof Char123LocaleChar125CrmRoute
  '/{-$locale}/customers': typeof Char123LocaleChar125CustomersRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/developers': typeof Char123LocaleChar125DevelopersRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRoute
  '/{-$locale}/downloads': typeof Char123LocaleChar125DownloadsRoute
  '/{-$locale}/gdpr': typeof Char123LocaleChar125GdprRoute
  '/{-$locale}/integrations': typeof Char123LocaleChar125IntegrationsRoute
  '/{-$locale}/llm-info': typeof Char123LocaleChar125LlmInfoRoute
  '/{-$locale}/messaging': typeof Char123LocaleChar125MessagingRoute
  '/{-$locale}/partners': typeof Char123LocaleChar125PartnersRoute
  '/{-$locale}/phone-menu': typeof Char123LocaleChar125PhoneMenuRoute
  '/{-$locale}/port-your-number': typeof Char123LocaleChar125PortYourNumberRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/refund': typeof Char123LocaleChar125RefundRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/security': typeof Char123LocaleChar125SecurityRoute
  '/{-$locale}/shared-numbers': typeof Char123LocaleChar125SharedNumbersRoute
  '/{-$locale}/status': typeof Char123LocaleChar125StatusRoute
  '/{-$locale}/tasks': typeof Char123LocaleChar125TasksRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/public/rates-sheet': typeof ApiPublicRatesSheetRoute
  '/{-$locale}/rates/$countrySlug': typeof Char123LocaleChar125RatesCountrySlugRoute
  '/{-$locale}/solutions/education': typeof Char123LocaleChar125SolutionsEducationRoute
  '/{-$locale}/solutions/franchise': typeof Char123LocaleChar125SolutionsFranchiseRoute
  '/{-$locale}/solutions/healthcare': typeof Char123LocaleChar125SolutionsHealthcareRoute
  '/{-$locale}/solutions/home-services': typeof Char123LocaleChar125SolutionsHomeServicesRoute
  '/{-$locale}/solutions/law-firms': typeof Char123LocaleChar125SolutionsLawFirmsRoute
  '/{-$locale}/solutions/operations': typeof Char123LocaleChar125SolutionsOperationsRoute
  '/{-$locale}/solutions/property-management': typeof Char123LocaleChar125SolutionsPropertyManagementRoute
  '/{-$locale}/solutions/sales': typeof Char123LocaleChar125SolutionsSalesRoute
  '/{-$locale}/solutions/small-business': typeof Char123LocaleChar125SolutionsSmallBusinessRoute
  '/{-$locale}/solutions/startups': typeof Char123LocaleChar125SolutionsStartupsRoute
  '/{-$locale}/solutions/support': typeof Char123LocaleChar125SolutionsSupportRoute
  '/{-$locale}/rates/': typeof Char123LocaleChar125RatesIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/ai-agent': typeof Char123LocaleChar125AiAgentRoute
  '/{-$locale}/analytics': typeof Char123LocaleChar125AnalyticsRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRoute
  '/{-$locale}/calling': typeof Char123LocaleChar125CallingRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/connectivity': typeof Char123LocaleChar125ConnectivityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/crm': typeof Char123LocaleChar125CrmRoute
  '/{-$locale}/customers': typeof Char123LocaleChar125CustomersRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/developers': typeof Char123LocaleChar125DevelopersRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRoute
  '/{-$locale}/downloads': typeof Char123LocaleChar125DownloadsRoute
  '/{-$locale}/gdpr': typeof Char123LocaleChar125GdprRoute
  '/{-$locale}/integrations': typeof Char123LocaleChar125IntegrationsRoute
  '/{-$locale}/llm-info': typeof Char123LocaleChar125LlmInfoRoute
  '/{-$locale}/messaging': typeof Char123LocaleChar125MessagingRoute
  '/{-$locale}/partners': typeof Char123LocaleChar125PartnersRoute
  '/{-$locale}/phone-menu': typeof Char123LocaleChar125PhoneMenuRoute
  '/{-$locale}/port-your-number': typeof Char123LocaleChar125PortYourNumberRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/refund': typeof Char123LocaleChar125RefundRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/security': typeof Char123LocaleChar125SecurityRoute
  '/{-$locale}/shared-numbers': typeof Char123LocaleChar125SharedNumbersRoute
  '/{-$locale}/status': typeof Char123LocaleChar125StatusRoute
  '/{-$locale}/tasks': typeof Char123LocaleChar125TasksRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/public/rates-sheet': typeof ApiPublicRatesSheetRoute
  '/{-$locale}/rates/$countrySlug': typeof Char123LocaleChar125RatesCountrySlugRoute
  '/{-$locale}/solutions/education': typeof Char123LocaleChar125SolutionsEducationRoute
  '/{-$locale}/solutions/franchise': typeof Char123LocaleChar125SolutionsFranchiseRoute
  '/{-$locale}/solutions/healthcare': typeof Char123LocaleChar125SolutionsHealthcareRoute
  '/{-$locale}/solutions/home-services': typeof Char123LocaleChar125SolutionsHomeServicesRoute
  '/{-$locale}/solutions/law-firms': typeof Char123LocaleChar125SolutionsLawFirmsRoute
  '/{-$locale}/solutions/operations': typeof Char123LocaleChar125SolutionsOperationsRoute
  '/{-$locale}/solutions/property-management': typeof Char123LocaleChar125SolutionsPropertyManagementRoute
  '/{-$locale}/solutions/sales': typeof Char123LocaleChar125SolutionsSalesRoute
  '/{-$locale}/solutions/small-business': typeof Char123LocaleChar125SolutionsSmallBusinessRoute
  '/{-$locale}/solutions/startups': typeof Char123LocaleChar125SolutionsStartupsRoute
  '/{-$locale}/solutions/support': typeof Char123LocaleChar125SolutionsSupportRoute
  '/{-$locale}/rates': typeof Char123LocaleChar125RatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/ai-agent': typeof Char123LocaleChar125AiAgentRoute
  '/{-$locale}/analytics': typeof Char123LocaleChar125AnalyticsRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRoute
  '/{-$locale}/calling': typeof Char123LocaleChar125CallingRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/connectivity': typeof Char123LocaleChar125ConnectivityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/crm': typeof Char123LocaleChar125CrmRoute
  '/{-$locale}/customers': typeof Char123LocaleChar125CustomersRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/developers': typeof Char123LocaleChar125DevelopersRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRoute
  '/{-$locale}/downloads': typeof Char123LocaleChar125DownloadsRoute
  '/{-$locale}/gdpr': typeof Char123LocaleChar125GdprRoute
  '/{-$locale}/integrations': typeof Char123LocaleChar125IntegrationsRoute
  '/{-$locale}/llm-info': typeof Char123LocaleChar125LlmInfoRoute
  '/{-$locale}/messaging': typeof Char123LocaleChar125MessagingRoute
  '/{-$locale}/partners': typeof Char123LocaleChar125PartnersRoute
  '/{-$locale}/phone-menu': typeof Char123LocaleChar125PhoneMenuRoute
  '/{-$locale}/port-your-number': typeof Char123LocaleChar125PortYourNumberRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/refund': typeof Char123LocaleChar125RefundRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/security': typeof Char123LocaleChar125SecurityRoute
  '/{-$locale}/shared-numbers': typeof Char123LocaleChar125SharedNumbersRoute
  '/{-$locale}/status': typeof Char123LocaleChar125StatusRoute
  '/{-$locale}/tasks': typeof Char123LocaleChar125TasksRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/public/rates-sheet': typeof ApiPublicRatesSheetRoute
  '/{-$locale}/rates/$countrySlug': typeof Char123LocaleChar125RatesCountrySlugRoute
  '/{-$locale}/solutions/education': typeof Char123LocaleChar125SolutionsEducationRoute
  '/{-$locale}/solutions/franchise': typeof Char123LocaleChar125SolutionsFranchiseRoute
  '/{-$locale}/solutions/healthcare': typeof Char123LocaleChar125SolutionsHealthcareRoute
  '/{-$locale}/solutions/home-services': typeof Char123LocaleChar125SolutionsHomeServicesRoute
  '/{-$locale}/solutions/law-firms': typeof Char123LocaleChar125SolutionsLawFirmsRoute
  '/{-$locale}/solutions/operations': typeof Char123LocaleChar125SolutionsOperationsRoute
  '/{-$locale}/solutions/property-management': typeof Char123LocaleChar125SolutionsPropertyManagementRoute
  '/{-$locale}/solutions/sales': typeof Char123LocaleChar125SolutionsSalesRoute
  '/{-$locale}/solutions/small-business': typeof Char123LocaleChar125SolutionsSmallBusinessRoute
  '/{-$locale}/solutions/startups': typeof Char123LocaleChar125SolutionsStartupsRoute
  '/{-$locale}/solutions/support': typeof Char123LocaleChar125SolutionsSupportRoute
  '/{-$locale}/rates/': typeof Char123LocaleChar125RatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/about'
    | '/{-$locale}/ai-agent'
    | '/{-$locale}/analytics'
    | '/{-$locale}/blog'
    | '/{-$locale}/calling'
    | '/{-$locale}/careers'
    | '/{-$locale}/connectivity'
    | '/{-$locale}/contact'
    | '/{-$locale}/crm'
    | '/{-$locale}/customers'
    | '/{-$locale}/demo'
    | '/{-$locale}/developers'
    | '/{-$locale}/docs'
    | '/{-$locale}/downloads'
    | '/{-$locale}/gdpr'
    | '/{-$locale}/integrations'
    | '/{-$locale}/llm-info'
    | '/{-$locale}/messaging'
    | '/{-$locale}/partners'
    | '/{-$locale}/phone-menu'
    | '/{-$locale}/port-your-number'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/refund'
    | '/{-$locale}/resources'
    | '/{-$locale}/security'
    | '/{-$locale}/shared-numbers'
    | '/{-$locale}/status'
    | '/{-$locale}/tasks'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/public/rates-sheet'
    | '/{-$locale}/rates/$countrySlug'
    | '/{-$locale}/solutions/education'
    | '/{-$locale}/solutions/franchise'
    | '/{-$locale}/solutions/healthcare'
    | '/{-$locale}/solutions/home-services'
    | '/{-$locale}/solutions/law-firms'
    | '/{-$locale}/solutions/operations'
    | '/{-$locale}/solutions/property-management'
    | '/{-$locale}/solutions/sales'
    | '/{-$locale}/solutions/small-business'
    | '/{-$locale}/solutions/startups'
    | '/{-$locale}/solutions/support'
    | '/{-$locale}/rates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/ai-agent'
    | '/{-$locale}/analytics'
    | '/{-$locale}/blog'
    | '/{-$locale}/calling'
    | '/{-$locale}/careers'
    | '/{-$locale}/connectivity'
    | '/{-$locale}/contact'
    | '/{-$locale}/crm'
    | '/{-$locale}/customers'
    | '/{-$locale}/demo'
    | '/{-$locale}/developers'
    | '/{-$locale}/docs'
    | '/{-$locale}/downloads'
    | '/{-$locale}/gdpr'
    | '/{-$locale}/integrations'
    | '/{-$locale}/llm-info'
    | '/{-$locale}/messaging'
    | '/{-$locale}/partners'
    | '/{-$locale}/phone-menu'
    | '/{-$locale}/port-your-number'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/refund'
    | '/{-$locale}/resources'
    | '/{-$locale}/security'
    | '/{-$locale}/shared-numbers'
    | '/{-$locale}/status'
    | '/{-$locale}/tasks'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/api/public/rates-sheet'
    | '/{-$locale}/rates/$countrySlug'
    | '/{-$locale}/solutions/education'
    | '/{-$locale}/solutions/franchise'
    | '/{-$locale}/solutions/healthcare'
    | '/{-$locale}/solutions/home-services'
    | '/{-$locale}/solutions/law-firms'
    | '/{-$locale}/solutions/operations'
    | '/{-$locale}/solutions/property-management'
    | '/{-$locale}/solutions/sales'
    | '/{-$locale}/solutions/small-business'
    | '/{-$locale}/solutions/startups'
    | '/{-$locale}/solutions/support'
    | '/{-$locale}/rates'
  id:
    | '__root__'
    | '/{-$locale}/about'
    | '/{-$locale}/ai-agent'
    | '/{-$locale}/analytics'
    | '/{-$locale}/blog'
    | '/{-$locale}/calling'
    | '/{-$locale}/careers'
    | '/{-$locale}/connectivity'
    | '/{-$locale}/contact'
    | '/{-$locale}/crm'
    | '/{-$locale}/customers'
    | '/{-$locale}/demo'
    | '/{-$locale}/developers'
    | '/{-$locale}/docs'
    | '/{-$locale}/downloads'
    | '/{-$locale}/gdpr'
    | '/{-$locale}/integrations'
    | '/{-$locale}/llm-info'
    | '/{-$locale}/messaging'
    | '/{-$locale}/partners'
    | '/{-$locale}/phone-menu'
    | '/{-$locale}/port-your-number'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/refund'
    | '/{-$locale}/resources'
    | '/{-$locale}/security'
    | '/{-$locale}/shared-numbers'
    | '/{-$locale}/status'
    | '/{-$locale}/tasks'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/public/rates-sheet'
    | '/{-$locale}/rates/$countrySlug'
    | '/{-$locale}/solutions/education'
    | '/{-$locale}/solutions/franchise'
    | '/{-$locale}/solutions/healthcare'
    | '/{-$locale}/solutions/home-services'
    | '/{-$locale}/solutions/law-firms'
    | '/{-$locale}/solutions/operations'
    | '/{-$locale}/solutions/property-management'
    | '/{-$locale}/solutions/sales'
    | '/{-$locale}/solutions/small-business'
    | '/{-$locale}/solutions/startups'
    | '/{-$locale}/solutions/support'
    | '/{-$locale}/rates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AiAgentRoute: typeof Char123LocaleChar125AiAgentRoute
  Char123LocaleChar125AnalyticsRoute: typeof Char123LocaleChar125AnalyticsRoute
  Char123LocaleChar125BlogRoute: typeof Char123LocaleChar125BlogRoute
  Char123LocaleChar125CallingRoute: typeof Char123LocaleChar125CallingRoute
  Char123LocaleChar125CareersRoute: typeof Char123LocaleChar125CareersRoute
  Char123LocaleChar125ConnectivityRoute: typeof Char123LocaleChar125ConnectivityRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125CrmRoute: typeof Char123LocaleChar125CrmRoute
  Char123LocaleChar125CustomersRoute: typeof Char123LocaleChar125CustomersRoute
  Char123LocaleChar125DemoRoute: typeof Char123LocaleChar125DemoRoute
  Char123LocaleChar125DevelopersRoute: typeof Char123LocaleChar125DevelopersRoute
  Char123LocaleChar125DocsRoute: typeof Char123LocaleChar125DocsRoute
  Char123LocaleChar125DownloadsRoute: typeof Char123LocaleChar125DownloadsRoute
  Char123LocaleChar125GdprRoute: typeof Char123LocaleChar125GdprRoute
  Char123LocaleChar125IntegrationsRoute: typeof Char123LocaleChar125IntegrationsRoute
  Char123LocaleChar125LlmInfoRoute: typeof Char123LocaleChar125LlmInfoRoute
  Char123LocaleChar125MessagingRoute: typeof Char123LocaleChar125MessagingRoute
  Char123LocaleChar125PartnersRoute: typeof Char123LocaleChar125PartnersRoute
  Char123LocaleChar125PhoneMenuRoute: typeof Char123LocaleChar125PhoneMenuRoute
  Char123LocaleChar125PortYourNumberRoute: typeof Char123LocaleChar125PortYourNumberRoute
  Char123LocaleChar125PricingRoute: typeof Char123LocaleChar125PricingRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125RefundRoute: typeof Char123LocaleChar125RefundRoute
  Char123LocaleChar125ResourcesRoute: typeof Char123LocaleChar125ResourcesRoute
  Char123LocaleChar125SecurityRoute: typeof Char123LocaleChar125SecurityRoute
  Char123LocaleChar125SharedNumbersRoute: typeof Char123LocaleChar125SharedNumbersRoute
  Char123LocaleChar125StatusRoute: typeof Char123LocaleChar125StatusRoute
  Char123LocaleChar125TasksRoute: typeof Char123LocaleChar125TasksRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ApiPublicRatesSheetRoute: typeof ApiPublicRatesSheetRoute
  Char123LocaleChar125RatesCountrySlugRoute: typeof Char123LocaleChar125RatesCountrySlugRoute
  Char123LocaleChar125SolutionsEducationRoute: typeof Char123LocaleChar125SolutionsEducationRoute
  Char123LocaleChar125SolutionsFranchiseRoute: typeof Char123LocaleChar125SolutionsFranchiseRoute
  Char123LocaleChar125SolutionsHealthcareRoute: typeof Char123LocaleChar125SolutionsHealthcareRoute
  Char123LocaleChar125SolutionsHomeServicesRoute: typeof Char123LocaleChar125SolutionsHomeServicesRoute
  Char123LocaleChar125SolutionsLawFirmsRoute: typeof Char123LocaleChar125SolutionsLawFirmsRoute
  Char123LocaleChar125SolutionsOperationsRoute: typeof Char123LocaleChar125SolutionsOperationsRoute
  Char123LocaleChar125SolutionsPropertyManagementRoute: typeof Char123LocaleChar125SolutionsPropertyManagementRoute
  Char123LocaleChar125SolutionsSalesRoute: typeof Char123LocaleChar125SolutionsSalesRoute
  Char123LocaleChar125SolutionsSmallBusinessRoute: typeof Char123LocaleChar125SolutionsSmallBusinessRoute
  Char123LocaleChar125SolutionsStartupsRoute: typeof Char123LocaleChar125SolutionsStartupsRoute
  Char123LocaleChar125SolutionsSupportRoute: typeof Char123LocaleChar125SolutionsSupportRoute
  Char123LocaleChar125RatesIndexRoute: typeof Char123LocaleChar125RatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/{-$locale}/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/ai-agent': {
      id: '/{-$locale}/ai-agent'
      path: '/{-$locale}/ai-agent'
      fullPath: '/{-$locale}/ai-agent'
      preLoaderRoute: typeof Char123LocaleChar125AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/analytics': {
      id: '/{-$locale}/analytics'
      path: '/{-$locale}/analytics'
      fullPath: '/{-$locale}/analytics'
      preLoaderRoute: typeof Char123LocaleChar125AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/calling': {
      id: '/{-$locale}/calling'
      path: '/{-$locale}/calling'
      fullPath: '/{-$locale}/calling'
      preLoaderRoute: typeof Char123LocaleChar125CallingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/careers': {
      id: '/{-$locale}/careers'
      path: '/{-$locale}/careers'
      fullPath: '/{-$locale}/careers'
      preLoaderRoute: typeof Char123LocaleChar125CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/connectivity': {
      id: '/{-$locale}/connectivity'
      path: '/{-$locale}/connectivity'
      fullPath: '/{-$locale}/connectivity'
      preLoaderRoute: typeof Char123LocaleChar125ConnectivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/{-$locale}/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/crm': {
      id: '/{-$locale}/crm'
      path: '/{-$locale}/crm'
      fullPath: '/{-$locale}/crm'
      preLoaderRoute: typeof Char123LocaleChar125CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/customers': {
      id: '/{-$locale}/customers'
      path: '/{-$locale}/customers'
      fullPath: '/{-$locale}/customers'
      preLoaderRoute: typeof Char123LocaleChar125CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/demo': {
      id: '/{-$locale}/demo'
      path: '/{-$locale}/demo'
      fullPath: '/{-$locale}/demo'
      preLoaderRoute: typeof Char123LocaleChar125DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/developers': {
      id: '/{-$locale}/developers'
      path: '/{-$locale}/developers'
      fullPath: '/{-$locale}/developers'
      preLoaderRoute: typeof Char123LocaleChar125DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs': {
      id: '/{-$locale}/docs'
      path: '/{-$locale}/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/downloads': {
      id: '/{-$locale}/downloads'
      path: '/{-$locale}/downloads'
      fullPath: '/{-$locale}/downloads'
      preLoaderRoute: typeof Char123LocaleChar125DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/gdpr': {
      id: '/{-$locale}/gdpr'
      path: '/{-$locale}/gdpr'
      fullPath: '/{-$locale}/gdpr'
      preLoaderRoute: typeof Char123LocaleChar125GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/integrations': {
      id: '/{-$locale}/integrations'
      path: '/{-$locale}/integrations'
      fullPath: '/{-$locale}/integrations'
      preLoaderRoute: typeof Char123LocaleChar125IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/llm-info': {
      id: '/{-$locale}/llm-info'
      path: '/{-$locale}/llm-info'
      fullPath: '/{-$locale}/llm-info'
      preLoaderRoute: typeof Char123LocaleChar125LlmInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/messaging': {
      id: '/{-$locale}/messaging'
      path: '/{-$locale}/messaging'
      fullPath: '/{-$locale}/messaging'
      preLoaderRoute: typeof Char123LocaleChar125MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/partners': {
      id: '/{-$locale}/partners'
      path: '/{-$locale}/partners'
      fullPath: '/{-$locale}/partners'
      preLoaderRoute: typeof Char123LocaleChar125PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/phone-menu': {
      id: '/{-$locale}/phone-menu'
      path: '/{-$locale}/phone-menu'
      fullPath: '/{-$locale}/phone-menu'
      preLoaderRoute: typeof Char123LocaleChar125PhoneMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/port-your-number': {
      id: '/{-$locale}/port-your-number'
      path: '/{-$locale}/port-your-number'
      fullPath: '/{-$locale}/port-your-number'
      preLoaderRoute: typeof Char123LocaleChar125PortYourNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/pricing': {
      id: '/{-$locale}/pricing'
      path: '/{-$locale}/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/{-$locale}/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/refund': {
      id: '/{-$locale}/refund'
      path: '/{-$locale}/refund'
      fullPath: '/{-$locale}/refund'
      preLoaderRoute: typeof Char123LocaleChar125RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/resources': {
      id: '/{-$locale}/resources'
      path: '/{-$locale}/resources'
      fullPath: '/{-$locale}/resources'
      preLoaderRoute: typeof Char123LocaleChar125ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/security': {
      id: '/{-$locale}/security'
      path: '/{-$locale}/security'
      fullPath: '/{-$locale}/security'
      preLoaderRoute: typeof Char123LocaleChar125SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/shared-numbers': {
      id: '/{-$locale}/shared-numbers'
      path: '/{-$locale}/shared-numbers'
      fullPath: '/{-$locale}/shared-numbers'
      preLoaderRoute: typeof Char123LocaleChar125SharedNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/status': {
      id: '/{-$locale}/status'
      path: '/{-$locale}/status'
      fullPath: '/{-$locale}/status'
      preLoaderRoute: typeof Char123LocaleChar125StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/tasks': {
      id: '/{-$locale}/tasks'
      path: '/{-$locale}/tasks'
      fullPath: '/{-$locale}/tasks'
      preLoaderRoute: typeof Char123LocaleChar125TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/{-$locale}/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rates-sheet': {
      id: '/api/public/rates-sheet'
      path: '/api/public/rates-sheet'
      fullPath: '/api/public/rates-sheet'
      preLoaderRoute: typeof ApiPublicRatesSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/rates/': {
      id: '/{-$locale}/rates/'
      path: '/{-$locale}/rates'
      fullPath: '/{-$locale}/rates/'
      preLoaderRoute: typeof Char123LocaleChar125RatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/rates/$countrySlug': {
      id: '/{-$locale}/rates/$countrySlug'
      path: '/{-$locale}/rates/$countrySlug'
      fullPath: '/{-$locale}/rates/$countrySlug'
      preLoaderRoute: typeof Char123LocaleChar125RatesCountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/education': {
      id: '/{-$locale}/solutions/education'
      path: '/{-$locale}/solutions/education'
      fullPath: '/{-$locale}/solutions/education'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/franchise': {
      id: '/{-$locale}/solutions/franchise'
      path: '/{-$locale}/solutions/franchise'
      fullPath: '/{-$locale}/solutions/franchise'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsFranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/healthcare': {
      id: '/{-$locale}/solutions/healthcare'
      path: '/{-$locale}/solutions/healthcare'
      fullPath: '/{-$locale}/solutions/healthcare'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/home-services': {
      id: '/{-$locale}/solutions/home-services'
      path: '/{-$locale}/solutions/home-services'
      fullPath: '/{-$locale}/solutions/home-services'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsHomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/law-firms': {
      id: '/{-$locale}/solutions/law-firms'
      path: '/{-$locale}/solutions/law-firms'
      fullPath: '/{-$locale}/solutions/law-firms'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsLawFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/operations': {
      id: '/{-$locale}/solutions/operations'
      path: '/{-$locale}/solutions/operations'
      fullPath: '/{-$locale}/solutions/operations'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/property-management': {
      id: '/{-$locale}/solutions/property-management'
      path: '/{-$locale}/solutions/property-management'
      fullPath: '/{-$locale}/solutions/property-management'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsPropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/sales': {
      id: '/{-$locale}/solutions/sales'
      path: '/{-$locale}/solutions/sales'
      fullPath: '/{-$locale}/solutions/sales'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/small-business': {
      id: '/{-$locale}/solutions/small-business'
      path: '/{-$locale}/solutions/small-business'
      fullPath: '/{-$locale}/solutions/small-business'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsSmallBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/startups': {
      id: '/{-$locale}/solutions/startups'
      path: '/{-$locale}/solutions/startups'
      fullPath: '/{-$locale}/solutions/startups'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/solutions/support': {
      id: '/{-$locale}/solutions/support'
      path: '/{-$locale}/solutions/support'
      fullPath: '/{-$locale}/solutions/support'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125AiAgentRoute: Char123LocaleChar125AiAgentRoute,
  Char123LocaleChar125AnalyticsRoute: Char123LocaleChar125AnalyticsRoute,
  Char123LocaleChar125BlogRoute: Char123LocaleChar125BlogRoute,
  Char123LocaleChar125CallingRoute: Char123LocaleChar125CallingRoute,
  Char123LocaleChar125CareersRoute: Char123LocaleChar125CareersRoute,
  Char123LocaleChar125ConnectivityRoute: Char123LocaleChar125ConnectivityRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125CrmRoute: Char123LocaleChar125CrmRoute,
  Char123LocaleChar125CustomersRoute: Char123LocaleChar125CustomersRoute,
  Char123LocaleChar125DemoRoute: Char123LocaleChar125DemoRoute,
  Char123LocaleChar125DevelopersRoute: Char123LocaleChar125DevelopersRoute,
  Char123LocaleChar125DocsRoute: Char123LocaleChar125DocsRoute,
  Char123LocaleChar125DownloadsRoute: Char123LocaleChar125DownloadsRoute,
  Char123LocaleChar125GdprRoute: Char123LocaleChar125GdprRoute,
  Char123LocaleChar125IntegrationsRoute: Char123LocaleChar125IntegrationsRoute,
  Char123LocaleChar125LlmInfoRoute: Char123LocaleChar125LlmInfoRoute,
  Char123LocaleChar125MessagingRoute: Char123LocaleChar125MessagingRoute,
  Char123LocaleChar125PartnersRoute: Char123LocaleChar125PartnersRoute,
  Char123LocaleChar125PhoneMenuRoute: Char123LocaleChar125PhoneMenuRoute,
  Char123LocaleChar125PortYourNumberRoute:
    Char123LocaleChar125PortYourNumberRoute,
  Char123LocaleChar125PricingRoute: Char123LocaleChar125PricingRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125RefundRoute: Char123LocaleChar125RefundRoute,
  Char123LocaleChar125ResourcesRoute: Char123LocaleChar125ResourcesRoute,
  Char123LocaleChar125SecurityRoute: Char123LocaleChar125SecurityRoute,
  Char123LocaleChar125SharedNumbersRoute:
    Char123LocaleChar125SharedNumbersRoute,
  Char123LocaleChar125StatusRoute: Char123LocaleChar125StatusRoute,
  Char123LocaleChar125TasksRoute: Char123LocaleChar125TasksRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ApiPublicRatesSheetRoute: ApiPublicRatesSheetRoute,
  Char123LocaleChar125RatesCountrySlugRoute:
    Char123LocaleChar125RatesCountrySlugRoute,
  Char123LocaleChar125SolutionsEducationRoute:
    Char123LocaleChar125SolutionsEducationRoute,
  Char123LocaleChar125SolutionsFranchiseRoute:
    Char123LocaleChar125SolutionsFranchiseRoute,
  Char123LocaleChar125SolutionsHealthcareRoute:
    Char123LocaleChar125SolutionsHealthcareRoute,
  Char123LocaleChar125SolutionsHomeServicesRoute:
    Char123LocaleChar125SolutionsHomeServicesRoute,
  Char123LocaleChar125SolutionsLawFirmsRoute:
    Char123LocaleChar125SolutionsLawFirmsRoute,
  Char123LocaleChar125SolutionsOperationsRoute:
    Char123LocaleChar125SolutionsOperationsRoute,
  Char123LocaleChar125SolutionsPropertyManagementRoute:
    Char123LocaleChar125SolutionsPropertyManagementRoute,
  Char123LocaleChar125SolutionsSalesRoute:
    Char123LocaleChar125SolutionsSalesRoute,
  Char123LocaleChar125SolutionsSmallBusinessRoute:
    Char123LocaleChar125SolutionsSmallBusinessRoute,
  Char123LocaleChar125SolutionsStartupsRoute:
    Char123LocaleChar125SolutionsStartupsRoute,
  Char123LocaleChar125SolutionsSupportRoute:
    Char123LocaleChar125SolutionsSupportRoute,
  Char123LocaleChar125RatesIndexRoute: Char123LocaleChar125RatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
